version = 0.1
[default]
[default.deploy]
[default.deploy.parameters]
stack_name = "sam-api-project"
region = "us-east-1"
confirm_changeset = true
capabilities = "CAPABILITY_IAM"
image_repositories = []
resolve_s3 = true
profile = "personal"